## Note, "[ci skio]" or "[skip ci]" within a commit message _should_
##  cause Travis Continuous Integration to skip the following

## Thanks be to
##  https://docs.travis-ci.com/user/languages/rust/


## Clone settings for repository
##   1. Reduce log _fluff_ with `true`
##   2. Clone submodules when cloning this branch with `true`
##   3. Clone the whole Git history with `false`, or set integer limit
git:
  quite: false
  submodules: false
  depth: false


## The dialect that will be spoken
##   1. Really what Jest speaks
##   2. Version(s) of `node_js` to target
language: rust
rust:
  - stable


## Operating systems to spin-up
##   1. When `true` some blocks such as `script` terminates at first failure
##   2. List of OS configurations (FrontMater _blocks_) Travis should test with
matrix:
  fast_finish: true
  include:
    ## Default 'dist' was 'trusty' as of 2019
    - name: 'Linux Xenial'
      os: linux
      dist: xenial


## Retrict what branches are cloned with Git
##   1. Fetch `only` `main` or _`test-`_ prefixed branches
##   2. Specifically ignore fetching the `gh-pages` branch
branches:
  only:
    - main
    - /^(?i:test)-.*$/
  except:
    - gh-pages


## Install dependencies and run tests
script:
  - cargo test --verbose
  - cargo run --example compare-versions '1.14.3' '-lt' '1.14.4'
  - cargo run --example math-versions '1.14.3' '-add' '1.14.4'


